### ISSUE TITLE
README examples for using kitchen.

### ISSUE THREAD

**Issue by xacaxulu** [chef/vagrant-omnibus#116]
I would really appreciate some examples of how to use this with test kitchen, specifically, how to modify the .kitchen.yml file to effect similar changes that are present in the current Vagrantfile examples.

**Comment by tmatilai** [comment]
Hi @xacaxulu,

Test Kitchen does not generate Chef provision configuration for its Vagrantfile, so vagrant-omnibus is not even used there. Instead Test Kitchen runs Chef all by itself after spinning up the VM.

Anyway, you can have very similar behavior in Test Kitchen. Examples:

```yaml
provisioner:
  name: chef_zero
  require_chef_omnibus: true
```

```yaml
provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18.6
```

More examples and documentation can be found at least here: https://docs.chef.io/config_yml_kitchen.html
